### ISSUE TITLE
ValueError:  No file descriptor for the version c8c2600 of FiniteSets.

### ISSUE THREAD

**Issue by soimort** [apkgbot/package-index#19]
When trying to `apkg init` on a clean machine (with the latest version of `agda-pkg`), the following error raises:

```
$ apkg init     
Indexing libraries from https://github.com/agda/package-index.git
  Current version of the index: 232ddbdffdb21093529c03be71140b2c91353447
Traceback (most recent call last):
  File "/home/soimort/.local/bin/apkg", line 11, in <module>
    load_entry_point('agda-pkg==0.1.45', 'console_scripts', 'apkg')()
  File "/home/soimort/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/soimort/.local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/soimort/.local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/soimort/.local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/soimort/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/soimort/.local/lib/python3.8/site-packages/apkg/commands/init.py", line 95, in init
    info = version.readInfoFromLibFile()
  File "/home/soimort/.local/lib/python3.8/site-packages/apkg/service/database.py", line 276, in readInfoFromLibFile
    return readLibFile(self.getLibFilePath())
  File "/home/soimort/.local/lib/python3.8/site-packages/apkg/service/database.py", line 237, in getLibFilePath
    raise ValueError(" No file descriptor for the version {} of {}."
ValueError:  No file descriptor for the version c8c2600 of FiniteSets.
```

Obviously it was looking for a file under `package-index/src/FiniteSets/versions/c8c2600/FiniteSets.agda-lib`, which doesn't exist. (the actual filename is `finiteSets.agda-lib`.)

**Comment by jonaprieto** [comment]
Hey, thanks for reporting this. I couldn't reproduce this issue with apkg v0.1.46 but I just fixed the rename.

**Comment by jonaprieto** [comment]
Please open it if the error persists.
